### ISSUE TITLE
Director crashes if $schema is used in cypress.json

### ISSUE THREAD

**Issue by BradenM** [agoldis/sorry-cypress#38]
Hi, thanks for this awesome project! Wanted to let you know about a (minor) issue I ran into.

**Problem**
Director crashes with if `UnhandledPromiseRejectionWarning` `$schema` is used in `cypress.json`.
Locally, the run stalls with a HTTP 500 error.

**Workaround**
Simply remove `$schema` from `cypress.json` for now.

**Possible Solution**
Via the director side, ignore `$schema` if found in config file.

**Traceback**

Logs from cloudwatch in the director stream:
```
(node:19) UnhandledPromiseRejectionWarning: MongoError: The dollar ($) prefixed field '$schema' in 'results.cypressConfig.$schema' is not valid for storage.
    at Function.create (/app/node_modules/mongodb/lib/core/error.js:43:12)
    at toError (/app/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.update (/app/node_modules/mongodb/lib/operations/common_functions.js:376:39)
    at /app/node_modules/mongodb/lib/core/connection/pool.js:404:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> Received instance result { instanceId: '2cfa93df-7f77-47d8-af8e-5ffe35a44db9' }
(node:19) UnhandledPromiseRejectionWarning: MongoError: The dollar ($) prefixed field '$schema' in 'results.cypressConfig.$schema' is not valid for storage.
    at Function.create (/app/node_modules/mongodb/lib/core/error.js:43:12)
    at toError (/app/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.update (/app/node_modules/mongodb/lib/operations/common_functions.js:376:39)
    at /app/node_modules/mongodb/lib/core/connection/pool.js:404:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Config File**

Command: `cypress run --parallel --record --key xxxx --ci-build-id "local-cy-test-run"`

`cypress.json`:
```json
{
  "$schema": "https://on.cypress.io/cypress.schema.json",
  "baseUrl": "http://localhost:8080",
  "env": {
    "NODE_ENV": "test",
    "VUE_APP_API_BASE_URL": "http://localhost:5000",
    "API_URL": "http://localhost:5000"
  },
  "ignoreTestFiles": ["**/__snapshots__/*", "**/__image_snapshots__/*"],
  "projectId": "xxxx",
  "viewportHeight": 900,
  "viewportWidth": 1400
}

```

**Comment by agoldis** [comment]
Thanks for discovering the issue! 👍

**Comment by agoldis** [comment]
Released in https://github.com/agoldis/sorry-cypress/releases/tag/v0.2.2
