### ISSUE TITLE
[K8S] director failed connect to mongo after pod re-deploy

### ISSUE THREAD

**Issue by pshynin** [agoldis/sorry-cypress#49]
Running sorry-cypress in k8s with ArgoCD. Simply used provided docker-compose .yaml file to generate k8s deployment manifests. mongo deployed as a pod (not a good practice tho, will move to aws rds once figure this out). Hence with K8S pods are destroyed and re-created from time to time which caused an issue for director service to connect.

After re-deploy Cypress throws error while trying to run the test:
```
We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

RequestError: Error: socket hang up
We encountered an unexpected error talking to our servers.

We will retry 2 more times in 1 minute...
```

And director pod throws exception:
```
>> Machine is asking to join a run { recordKey: 'xxx', ciBuildId: 'Local Build: 01' }
>> Machine is joining a run { ciBuildId: 'Local Build: 01' }
(node:27) UnhandledPromiseRejectionWarning: MongoError: server instance pool was destroyed
    at basicWriteValidations (/app/node_modules/mongodb/lib/core/topologies/server.js:574:41)
    at Server.insert (/app/node_modules/mongodb/lib/core/topologies/server.js:688:16)
    at Server.insert (/app/node_modules/mongodb/lib/topologies/topology_base.js:301:25)
    at insertDocuments (/app/node_modules/mongodb/lib/operations/common_functions.js:259:19)
    at InsertOneOperation.execute (/app/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/app/node_modules/mongodb/lib/collection.js:516:10)
    at createRun (/app/dist/execution/mongo/runs/run.model.js:24:59)
    at Object.createRun (/app/dist/execution/mongo/runs/run.controller.js:33:30)
    at app.post (/app/dist/app.js:47:53)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t
hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled
 with .catch(). (rejection id: 54)
```

mongo pod seems started successfully and connected successfully:
```
2020-04-13T22:56:09.516+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total re
cords. 0 secs
2020-04-13T22:56:10.000+0000 I SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <u
nsharded>
2020-04-13T22:56:10.307+0000 I NETWORK  [listener] connection accepted from 10.13.56.18:37516 #1 (1 connec
tion now open)
2020-04-13T22:56:10.308+0000 I NETWORK  [conn1] received client metadata from 10.13.56.18:37516 conn1: { d
river: { name: "nodejs", version: "3.5.5" }, os: { type: "Linux", name: "linux", architecture: "x64", vers
ion: "4.14.146-119.123.amzn2.x86_64" }, platform: "'Node.js v10.19.0, LE (legacy)" }
2020-04-13T23:01:09.504+0000 I SHARDING [LogicalSessionCacheReap] Marking collection config.transactions a
s collection version: <unsharded>
2020-04-13T23:22:32.821+0000 I SHARDING [conn1] Marking collection sorry-cypress.runs as collection versio
n: <unsharded>
```

Still investigating... I saw the same issue reported few times for cypress dashboard as well, so it might be not a dashboard related. However decided to log this to keep track.

**Comment by zx86496790** [comment]
new to this. got an error saying  Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
please help

**Comment by pshynin** [comment]
not using docker-compose. I used it only as a templated to create K8S deployment manifests. There are workarounds but its anyway better to no run database in K8S, hence I am working on AWS RDS deployment for mongo.. 
closing this, since it's K8S related, not a dashboard app. 
Thanks for building this app, very cool stuff !
